### ISSUE TITLE
[TTRevamp] ToDo

### ISSUE THREAD

**Issue by mosemister** [TerraTerma/TTCore#1]
All new features that will come with the revamp. Please note that the first tick is if it is programmed in, the 2nd tick is if it has been tested for the release version.

**TTCore**
- [ ] 
- [ ] The Storing of default data from the Player to modify while the player is offline (storing information such as DisplayName, last known location, etc.)
- [x] 
- [ ] The mech API 2.2 for players and civilizations
- [x] 
- [ ] The query command
-[x]
- [ ] version control over all parts of the TTSystem
- [ ] 
- [ ] Inventory API 2.0

**TTModLog**
- [x] 
- [ ] The logging of actions of players for reporting purposes only

**TTAbilities**
- [x] 
- [ ] add the ability to run really fast for a few seconds
- [ ] 
- [ ] add the ability to pick up non human entities and keep them in staces around you (and fire when it is turned off)

**TTChatSystem**
- [x] 
- [ ] player programmable chat formats
- [ ] 
- [ ] re-adding the chat games

**TTAchivements**
- [x] 
- [ ] add easy to get one time achievements
- [x] 
- [ ] add difficult multi get achievements

**Civilisation**
- [x] 
- [ ] The ability to create protection chunks known as civilisation
- [ ] 
- [ ] The civilisations being block place and break protected from people inside and outside the civilisation
- [x] 
- [ ] The civilisation being protected from creature based entity
- [ ] 
- [ ] The civilisation being protected from internal and external Ships
- [x] 
- [ ] The ability to use a command to create civilisations
- [x] 
- [ ] The ability to change the "flags" the civilisation has by commands
- [x] 
- [ ] The ability to change the "ranks" of a player inside the civilisation
- [ ] 
- [ ] The "worth" of a player changing based on killing of mobs and dieing (worth being "power" in factions)

**Ships - public release**
- [ ] 
- [ ] Ships 5.1.0.0/5.0.2.0

**Comment by JustMaffie** [comment]
Since when is ships part of tt plugins lol

**Comment by JustMaffie** [comment]
I am gonna work on the TTChatSystem for ChatGames then first

**Comment by mosemister** [comment]
Ships 5.1.0.0/5.0.2.0 was designed to release (a early copy of it) with the TTRevmap. Thats my department so dont even try and touch that unless you are hooking a plugin into it, then just listen to the events

**Comment by JustMaffie** [comment]
The chat formats are already done
